function [R] = GUI_44()

R = [];
S.fh = figure('units','pixels',...
              'position',[500 500 200 100],...
              'menubar','none',...
              'name','GUI_36',...              
              'numbertitle','off',...
              'resize','off');
S.ed = uicontrol('style','edit',...
                 'units','pix',...
                'position',[10 60 180 30],...
                'string','Deseja aplicar filtro e constraste na imagem ?');
S.pb = uicontrol('style','pushbutton',...
                 'units','pix',...
                'position',[10 20 180 30],...
                'string','Push to Return Data',...
                'callback',{@pb_call});
uicontrol(S.ed)  % Make the editbox active.
uiwait(S.fh)  % Prevent all other processes from starting until closed.

    function [] = pb_call(varargin)
    % Callback for the pushbutton.
        R = get(S.ed,'string');
        close(S.fh);  % Closes the GUI, allows the new R to be returned.
    end
end