function [A] = GUI_9()

S.fh = figure('units','pixels',...
              'position',[300 300 200 300],...
              'menubar','none',...
              'name','GUI',...
              'numbertitle','off',...
              'resize','off');

S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 230 160 60],...
                 'string','Carregar Imagem',...
                 'callback',{@pb_call},...
                 'backgroundc',[0.94 .94 .94],...
                 'busyaction','cancel',...% So multiple pushes don't stack.
                 'interrupt','off');
             
S.pb2 = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 160 160 60],...
                 'string','Apagar Linha',...
                 'callback',{@pb2_call},...
                 'backgroundc',[0.94 .94 .94],...
                 'busyaction','cancel',...% So multiple pushes don't stack.
                 'interrupt','off');
             
S.pb3 = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 90 160 60],...
                 'string','ScanLine',...
                 'callback',{@pb3_call},...
                 'backgroundc',[0.94 .94 .94],...
                 'busyaction','cancel',...% So multiple pushes don't stack.
                 'interrupt','off');
             
S.pb4 = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[20 20 160 60],...
                 'string','Sair',...
                 'callback',{@pb4_call},...
                 'backgroundc',[0.94 .94 .94],...
                 'busyaction','cancel',...% So multiple pushes don't stack.
                 'interrupt','off');
             
    function [] = pb_call(varargin)
        A = 1;
        close(S.fh);
    end
    function [] = pb2_call(varargin)
        A = 2;
        close(S.fh);
    end 
    function [] = pb3_call(varargin)
        A = 3;
        close(S.fh);
    end    
    function [] = pb4_call(varargin)
        A = 4;
        close(S.fh);
    end
end
